# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

- name: safety-inspection.eao-evidence-locker

  version: '1.0.0'
  description: The safety-inspection credential issued by EAO Evidence Locker
  path: /eao-evidence-locker/safety-inspection

  attributes:
    - corp_num
    - legal_name
    - permit_id
    - permit_type
    - permit_issued_date
    - permit_status
    - effective_date

### eof ###

